### ISSUE TITLE
Metar tab not working on v3 map

### ISSUE THREAD

**Issue by henrikp** [pigeond/fgmap#16]
Metar is working OK on the default page but on v3 it stays on "Loading METAR..." Tried with Firefox and Chrome.

**Comment by pigeond** [comment]
Which airport are you having trouble with? I just tried a few airports and they worked fine.

**Comment by vezza** [comment]
I also have this issue at EDDM

**Comment by pigeond** [comment]
Looks like metar has stopped working completely now. Will look into this soon.

**Comment by PigeonD-Wow** [comment]
Metar has been fixed once again.

**Comment by pigeond** [comment]
Metar has been fixed once again.
